name: Fetch CSVs from external repo → Release assets

on:
  push:
    branches:
      - feature/deploy-data
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: false # queue instead of cancel

jobs:
  fetch-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Install Python (venv)
        run: ./cli-setup-python.sh
